services:
  Davd:
    image: davd:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: davd_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/workspace
    shm_size: '8gb'
    